### ISSUE TITLE
warning or critical is not working for me

### ISSUE THREAD

**Issue by dermarzel** [SamK/check_iftraffic_nrpe.py#27]
Hey guys,

at first thanks a lot for this fantastic script. The output is great and also the fact to receive data for all interfaces is really nice.
Unfortunately I'm not getting warning or critical to work:

I'm trying the following command:

./check_iftraffic_nrpe.py -x lo -u Mbps -w 20 -c 40 -b 100
Traffic Mbps OK | in-eth0=98.0;20.0;40.0;0;100.0 out-eth0=2.4;20.0;40.0;0;100.0
echo $?
0

In my opinion the downgraded warning and critical values should trigger and the output should be something else and also the return code.
Am I doing anything wrong? Would be great to get this awesome script working completly like it's intended!

Thanks a lot and cheers
marzel

**Comment by stromnet** [comment]
+1 on for merging e41830baa77fd8bc490dab4800ae237f305cca57, it is required for alarming to work (i.e. make the script useful).

**Comment by SamK** [comment]
I'm on holiday right now (no access to my development environment). I'll be back in 2 weeks and finish the work.
