### ISSUE TITLE
Traffic MBps CRITICAL: Cannot write in /var/tmp/traffic_stats.dat ?

### ISSUE THREAD

**Issue by saljut7** [SamK/check_iftraffic_nrpe.py#31]
Hi

I've tried to set up check_iftraffic_nrpe.py this way

1. In `/usr/lib/nagios/plugins/` added:

```
wget https://raw.githubusercontent.com/SamK/check_iftraffic_nrpe.py/master/check_iftraffic_nrpe.py
```

2. In `vi /etc/nagios/nrpe.cfg` added:

```
command[check_traffic]=/usr/lib/nagios/plugins/check_iftraffic_nrpe.py -u MBps -i eth0 -b 2 -w 50 -c 80
```

3. Test/restart:

```
chmod +x /usr/lib/nagios/plugins/check_iftraffic_nrpe.py
/usr/lib/nagios/plugins//check_iftraffic_nrpe.py -x lo
service nagios-nrpe-server restart
```

(`/usr/lib/nagios/plugins//check_iftraffic_nrpe.py -x lo` works)

4. On MyNagiosServer:

In `/etc/nagios3/conf.d/server.cfg` added:

```
define service {
  use generic-service
  host_name MonitoredServerName
  service_description Net Traffic
  check_command check_nrpe_1arg!check_traffic
}
```

```
service nagios3 restart
```

Problem: Nagios says `Traffic MBps CRITICAL: Cannot write in /var/tmp/traffic_stats.dat.`

Is 

```
root@MyMonitoredServer:/var/tmp# ls -la
total 12
drwxrwxrwt  2 root root 4096 Apr 30 16:40 .
drwxr-xr-x 13 root root 4096 Dec 14 02:44 ..
-rw-r--r--  1 root root  712 Apr 30 16:28 traffic_stats.dat
```

not enough?

**Comment by SamK** [comment]
Hi,
This is a permission issue, you executed script as root and now the nagios service cannot write the file.

Just delete the file `/var/tmp/traffic_stats.dat` and let Nagios create it for you.

**Comment by saljut7** [comment]
Thx @SamK  - works fine now!
