### ISSUE TITLE
nrpe perfdata not consistent with python3

### ISSUE THREAD

**Issue by d3matt** [SamK/check_iftraffic_nrpe.py#32]
In python3, dictionary iteration is not consistent. This leads to icinga+pnp4nagios associating values incorrectly as it relies on consistent ordering in the perfdata.

Typical workarounds are to pass the call to .items() through sorted or to use OrderedDict which tracks the order items are inserted.

**Comment by SamK** [comment]
Hi,

I made a patch for your request. can you please test if you like it?
Please try to run the file in the [sort-perfdata](https://github.com/SamK/check_iftraffic_nrpe.py/tree/sort-perfdata) branch and let me know if it works for you.

**Comment by d3matt** [comment]
looks good

**Comment by SamK** [comment]
Merged into master.
I'm gonna release to pypi next week.
